In [3]:
import numpy as np
a = np.array([1,2,3,4,5,])
print(a)
print(type(a))
print(a.shape)
(print(a.ndim))

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [5]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
import timeit as time
Lst = range(1000)
print(Lst)
%timeit [i**2 for i in Lst]

range(0, 1000)
346 µs ± 531 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
L = np.arange(1000)   #the both codes are equivalent.
%timeit L**2

1.34 µs ± 19.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [31]:
a = np.array([1,2,3,4,5])  #pass a list
b = np.array((1,2,3,4,5))   #or pass a tuple
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [32]:
print(a.ndim)
print(a.shape)

1
(5,)


In [36]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c.shape)
print(c.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [39]:
d = np.array([[1,2,3],[4,5,6]])  #need to pass list of list.
print(d)

[[1 2 3]
 [4 5 6]]


In [42]:
arr = np.array(((1,2,3,4),(1,2,3,4)))
print(arr)

[[1 2 3 4]
 [1 2 3 4]]


In [46]:
m = np.arange(10,40,2)
print(m)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [52]:
m1 = np.linspace(0,1,5)  #out five radom number between 0 and 1, difference between consecutive number will be the same
print(m1)

[0.   0.25 0.5  0.75 1.  ]


In [57]:
m2 = np.ones((4,3))   #pass tuple for dimension of matrix 4*3
print(m2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [60]:
m3 = np.ones((3,3),dtype = int)
print (m3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
m4 = np.zeros((4,5),dtype = int)
print(m4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [66]:
m5 = np.eye(3,dtype = int)
print(m5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [70]:
m6 = np.eye(4,4,dtype = int)
print(m6)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [71]:
m6 = np.eye(4,4,-1,dtype = int)
print(m6)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [72]:
m7 = np.eye(4,4,1,dtype = int)
print(m7)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [73]:
m7 = np.diag([1,2,3,4])
m7

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [78]:
n = np.random.rand(4)
n

array([0.02123018, 0.87958765, 0.76742745, 0.5836583 ])